version: '3.8'
services:
  dice_be:
    image: emkaminsk/dice_be:latest
    ports:
      - 8081:8081
    command: ["python", "dice.py"]
    networks:
      - dice_network
  dice_fe:
    image: emkaminsk/dice_fe:latest
    ports:
      - 8000:8000
    networks:
      - dice_network

networks:
  dice_network:
    driver: bridge
